### ISSUE TITLE
autoconf does not point to the correct m4 binary

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/autoconfport#25]
```
autom4te: error: need GNU m4 1.4 or later: /usr/local/bin/m4
```

**Comment by MikeFultonDev** [comment]
@HarithaIBM This is still an issue. The code we download has:

```
my $m4 = $ENV{"M4"} || '/jenkins/prod/m4-1.4.19.20221106_231454.zos/bin/m4';
```

Not sure if you have had time to investigate but it causes problems for sed (although I expect I can work around it by defining M4 ?

**Comment by HarithaIBM** [comment]
@MikeFultonDev , Sure Mike! I will investigate this.

**Comment by MikeFultonDev** [comment]
@HarithaIBM is this fixed now with the changes we made to install to fix up paths, or is this still an issue?

**Comment by HarithaIBM** [comment]
Not an issue anymore, latest builds of sed port on jenkins is successful , so closing this.
