### ISSUE TITLE
running 'runbasic.sh' fails due to temporary makefile untagged

### ISSUE THREAD

**Issue by zopencommunity** [ZOSOpenTools/autoconfport#8]
running runbasic.sh results in:

```
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
configure with dependency tracking disabled did not run correctly
```

If we look at the generated files, trace files are untagged and config.log, config.status, and Makefile are tagged 1047. These should all be tagged ISO8859-1

```
find . -name "*" | xargs chtag -p 2>/dev/null | grep -v 8859 
- untagged    T=off ./basic/autom4te.cache/traces.0
- untagged    T=off ./basic/autom4te.cache/traces.1
- untagged    T=off ./basic/autom4te.cache/traces.2
t IBM-1047    T=on  ./basic/config.log
t IBM-1047    T=on  ./basic/config.status
t IBM-1047    T=on  ./basic/Makefile
```

**Comment by zopencommunity** [comment]
@IgorTodorovskiIBM fyi...

**Comment by zopencommunity** [comment]
digging into this some more led me over to 'm4'. Going through the m4 build process, I get to the following line:

cd lib/ && sed -e '/# am--include-marker/d' Makefile      | make -f - am--depfiles

being run from /fultonm/m4port/m4-1.4.19
The Makefile in question is in code page 1047, although changing it to code page ISO8859-1 didn't make a difference.

If I get rid of the pipe and write to a temporary file, everything works fine, so it appears that the IBM ported make is not correctly tagging the stream when it comes from stdin

@IgorTodorovskiIBM can you investigate?

**Comment by MikeFultonDev** [comment]
this is now working with @IgorTodorovskiIBM 's fix and using the make from makeport. I also moved this from autoconfport to automakeport
